package com.dingtalk.h5app.quickstart;

import com.dingtalk.h5app.quickstart.dto.CompanyDto;
import com.dingtalk.h5app.quickstart.model.Company;
import com.dingtalk.h5app.quickstart.model.staicdata.City;
import com.dingtalk.h5app.quickstart.model.staicdata.CompanyType;
import com.dingtalk.h5app.quickstart.model.staicdata.Industry;
import com.dingtalk.h5app.quickstart.model.staicdata.Province;
import com.dingtalk.h5app.quickstart.repository.CompanyRepository;
import com.dingtalk.h5app.quickstart.repository.staticdata.CityRepository;
import com.dingtalk.h5app.quickstart.repository.staticdata.IndustryRepository;
import com.dingtalk.h5app.quickstart.repository.staticdata.ProvinceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private CompanyRepository companyRepository;

    @Autowired
    private IndustryRepository industryRepository;

    @Autowired
    private CityRepository cityRepository;

    @Autowired
    private ProvinceRepository provinceRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/company")
    public @ResponseBody Iterable<CompanyDto> listCompany() {
        // This returns a JSON or XML with the users

//        Industry industry = new Industry();
//        industry.setName("行业1");
//        industry.setCategory("类别1");
//
//        Company company = new Company();
//        company.setName("company");
//        company.setIndustry(industry);
//
//        companyRepository.save(company);
        List<CompanyDto> companyDtos = new ArrayList<>();
        companyRepository.findAll().forEach(company -> companyDtos.add(new CompanyDto(company)));
        return  companyDtos;
    }

    @GetMapping(path="/industry")
    public @ResponseBody Iterable<Industry> listIndustry() {
        List<Industry> industries = (List<Industry>)industryRepository.findAll();

        for (Industry industry : industries) {
            System.out.println(industry);
        }
        return industries;
    }

    @GetMapping(path="/test")
    public @ResponseBody void test() {
//        Province province = new Province();
//        province.setName("辽宁");
//        Province p = provinceRepository.save(province);
//        City c1 = new City();
//        c1.setName("铁岭");
//        c1.setProvince(p);
//        City c2 = new City();
//        c2.setName("沈阳");
//        c2.setProvince(p);
//        cityRepository.save(c1);
//        cityRepository.save(c2);

        Industry industry = new Industry();
        industry.setName("金融");
        industry.setCategory("c1");

        industryRepository.save(industry);

        Company c = new Company();
        c.setName("公司1");
        c.setIndustry(industry);
        c.setType(CompanyType.technology);

        City city = cityRepository.findByName("沈阳");
        c.setCity(city);

        companyRepository.save(c);

    }
}